name: Deploy Docker

on:
  release:
    types: [published]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_DEPLOY }}
      - name: Get author name
        id: author
        run: echo "::set-output name=author::$(git show -s --format=%an)"
      - name: Print author name
        run: echo "${{ steps.author.outputs.author }}"
      - name: Get author name (sub)
        id: sub
        run: |
          RELEASE_TAG=$(cat "${{ github.ref }}" | cut -d '/' -f 3)
          echo "RELEASE_TAG=${{ RELEASE_TAG }}"
          echo "::set-output name=author::${{ RELEASE_TAG }}"
      - name: Print author name (sub)
        run: echo "${{ steps.sub.outputs.author }}"
      - name: Print author name with an environment variable
        run: echo $AUTHOR_NAME
        env:
          AUTHOR_NAME: ${{ steps.author.outputs.author }}
      - run: echo "$GITHUB_REF"
      - run: echo "$GITHUB_REF" | cut -d '/' -f 3
      - name: set output
        id: tag
        run: echo "::set-ouput name=tag::latest"
      - name: test output
        run: echo "${{ steps.tag.outputs.tag }}"
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
